apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mp-entity-manager.fullname" . }}
  labels:
    {{ include "mp-entity-manager.labels" . | nindent 4 }}
stringData:
  MP_ENTITY_MANAGER_DATABASE_PASSWORD: {{ required "A valid .Values.databasePassword entry required!" .Values.databasePassword }}
