# Enabling H2 Console: http://localhost:8080/h2-console
spring:
  profiles:
    active: DEV
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/h2/mp-entity-db:mp-testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: mp-user
    password: mp-pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop